
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package reporte;

/** CUP generated class containing symbol constants. */
public class ReporteSym {
  /* terminals */
  public static final int char_ = 57;
  public static final int menorque = 33;
  public static final int menos = 22;
  public static final int diagonaligual = 46;
  public static final int puntoycoma = 16;
  public static final int private_ = 49;
  public static final int parIzquierda = 12;
  public static final int punto = 18;
  public static final int tchar = 3;
  public static final int umasmas = 30;
  public static final int asterisco = 23;
  public static final int parDerecha = 13;
  public static final int porigual = 45;
  public static final int boolean_ = 58;
  public static final int for_ = 69;
  public static final int import_ = 73;
  public static final int continue_ = 66;
  public static final int mas = 21;
  public static final int dospuntos = 19;
  public static final int menorigual = 35;
  public static final int umenos = 26;
  public static final int else_ = 64;
  public static final int decimal = 5;
  public static final int umas = 27;
  public static final int interrogacion = 20;
  public static final int extends_ = 53;
  public static final int abstract_ = 50;
  public static final int do_ = 68;
  public static final int case_ = 71;
  public static final int masigual = 43;
  public static final int or = 39;
  public static final int mayorque = 32;
  public static final int menosigual = 44;
  public static final int static_ = 51;
  public static final int mayorigual = 34;
  public static final int id = 6;
  public static final int while_ = 67;
  public static final int llaveDerecha = 11;
  public static final int menosmenos = 29;
  public static final int break_ = 65;
  public static final int llaveIzquierda = 10;
  public static final int true_ = 8;
  public static final int and = 38;
  public static final int default_ = 72;
  public static final int xor = 41;
  public static final int void_ = 61;
  public static final int EOF = 0;
  public static final int if_ = 63;
  public static final int tstring = 2;
  public static final int return_ = 62;
  public static final int umenosmenos = 31;
  public static final int double_ = 56;
  public static final int error = 1;
  public static final int switch_ = 70;
  public static final int diferente = 37;
  public static final int public_ = 47;
  public static final int entero = 4;
  public static final int igualigual = 36;
  public static final int diagonal = 24;
  public static final int class_ = 54;
  public static final int println_ = 60;
  public static final int corcheteIzquierda = 14;
  public static final int new_ = 74;
  public static final int coma = 17;
  public static final int null_ = 7;
  public static final int modulo = 25;
  public static final int not = 40;
  public static final int final_ = 52;
  public static final int igual = 42;
  public static final int false_ = 9;
  public static final int print_ = 59;
  public static final int masmas = 28;
  public static final int int_ = 55;
  public static final int protected_ = 48;
  public static final int corcheteDerecha = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tstring",
  "tchar",
  "entero",
  "decimal",
  "id",
  "null_",
  "true_",
  "false_",
  "llaveIzquierda",
  "llaveDerecha",
  "parIzquierda",
  "parDerecha",
  "corcheteIzquierda",
  "corcheteDerecha",
  "puntoycoma",
  "coma",
  "punto",
  "dospuntos",
  "interrogacion",
  "mas",
  "menos",
  "asterisco",
  "diagonal",
  "modulo",
  "umenos",
  "umas",
  "masmas",
  "menosmenos",
  "umasmas",
  "umenosmenos",
  "mayorque",
  "menorque",
  "mayorigual",
  "menorigual",
  "igualigual",
  "diferente",
  "and",
  "or",
  "not",
  "xor",
  "igual",
  "masigual",
  "menosigual",
  "porigual",
  "diagonaligual",
  "public_",
  "protected_",
  "private_",
  "abstract_",
  "static_",
  "final_",
  "extends_",
  "class_",
  "int_",
  "double_",
  "char_",
  "boolean_",
  "print_",
  "println_",
  "void_",
  "return_",
  "if_",
  "else_",
  "break_",
  "continue_",
  "while_",
  "do_",
  "for_",
  "switch_",
  "case_",
  "default_",
  "import_",
  "new_"
  };
}

